### PR TITLE
Refactoring the javaewah

### PR DESCRIPTION
**Pull request by khushboopatel02**
I have refactored the javaewah code where I have used the extract class, extract method, move class, rename variable, move field, replace conditional with polymorphism as a part of my course study. It would be great if you can review the PR request and accept it.

### CODE REVIEW

**Comment by lemire** [comment]
Running tests.

**Comment by khushboopatel02** [comment]
Adding the Refactored Set II updated. Since previous one was failing the compilation

**Comment by khushboopatel02** [comment]
I have added the Refactored SET II after changing the refactor method. Can you please review the PR again

**Comment by lemire** [comment]
I have looked at the code and I'd like you to do is to break down the proposed changes and to justify each change. 

Acceptable changes should fall into one of these three categories generally...

1. Bug fixing.
2. Performance enhancement.
3. New features.

Other changes (e.g., coding style) are discouraged. It might still be acceptable, but you need to carefully justify the proposed change.

Refactoring in general is discouraged.

I am going to close this. I invite you to propose specific and justified changes.

**Pull request closed without merging**
